"""
Django settings for GoTravel project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from ast import literal_eval

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')dol^qfmb*zo78j^3dgmk416_2r1a#w=%5d(zvf5*eism+gptk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(literal_eval(os.environ.get("GT_DEBUG", "True")))
LOCAL = bool(literal_eval(os.environ.get("GT_LOCAL", "True")))
PROD = bool(literal_eval(os.environ.get("GT_PROD", "False")))

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'representation',
    'album',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'GoTravel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoTravel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
elif PROD:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',  # django.db.backends.postgresql_psycopg2
            'NAME': os.environ["GT_DB_DEFAULT_NAME"],
            'USER': os.environ["GT_DB_DEFAULT_USER"],
            'PASSWORD': os.environ["GT_DB_DEFAULT_PASSWORD"],
            'HOST': os.environ["GT_DB_DEFAULT_HOST"],
            'PORT': os.environ["GT_DB_DEFAULT_PORT"],
        }
    }
    STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/



if LOCAL:
    STATICFILES_DIRS = ([os.path.join(BASE_DIR, "static")])
elif PROD:
    STATIC_ROOT = os.path.join(PROJECT_ROOT, '../staticfiles')
    STATICFILES_DIRS = (
        os.path.join(PROJECT_ROOT, '../static'),
    )
STATIC_URL = '/static/'

AUTH_USER_MODEL = 'auth.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
