# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0006_auto_20160528_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to='representation.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_post', to='representation.UserProfile'),
        ),
    ]
